/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,mdx}", "*.{js,ts,jsx,tsx,mdx}"],
  safelist: [
    // Orange theme
    "bg-orange-600",
    "hover:bg-orange-700",
    "text-orange-600",
    "border-orange-600",
    "bg-orange-50",
    "bg-orange-100",
    "text-orange-700",
    "border-orange-200",
    "ring-orange-300",
    // Blue theme
    "bg-blue-primary",
    "hover:bg-blue-dark",
    "text-blue-primary",
    "border-blue-200",
    "bg-blue-light",
    "bg-blue-50",
    "text-blue-text",
    "border-blue-primary",
    "ring-blue-300",
    // Purple theme
    "bg-purple-primary",
    "hover:bg-purple-dark",
    "text-purple-primary",
    "border-purple-200",
    "bg-purple-light",
    "bg-purple-50",
    "text-purple-text",
    "border-purple-primary",
    "ring-purple-300",
    // Green theme
    "bg-green-primary",
    "hover:bg-green-dark",
    "text-green-primary",
    "border-green-200",
    "bg-green-light",
    "bg-green-50",
    "text-green-text",
    "border-green-primary",
    "ring-green-300",
    // Dark theme
    "bg-gray-800",
    "hover:bg-gray-900",
    "text-gray-800",
    "border-gray-600",
    "bg-dark-dark",
    "bg-dark-light",
    "text-dark-text",
    "border-dark-primary",
    "ring-gray-400",

    // General classes
    "text-gray-900",
    "text-gray-600",
    "bg-white",
    "bg-gray-50",
    "border-gray-200",
    "hover:bg-gray-100",
    "text-white",

    // Theme wrapper classes
    "theme-orange",
    "theme-blue",
    "theme-purple",
    "theme-green",
    "theme-dark",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        dark: "#1E1E1E",
        light: "#F8F8F8",
        "blue-primary": "#1E40AF",
        "blue-secondary": "#3B82F6",
        "blue-accent": "#60A5FA",
        "blue-light": "#EFF6FF",
        "blue-dark": "#1E3A8A",
        "blue-text": "#1F2937",
        "blue-muted": "#6B7280",
        "purple-primary": "#7C3AED",
        "purple-secondary": "#A855F7",
        "purple-accent": "#C084FC",
        "purple-light": "#FAF5FF",
        "purple-dark": "#581C87",
        "purple-text": "#1F2937",
        "purple-muted": "#6B7280",
        "green-primary": "#059669",
        "green-secondary": "#10B981",
        "green-accent": "#34D399",
        "green-light": "#ECFDF5",
        "green-dark": "#047857",
        "green-text": "#1F2937",
        "green-muted": "#6B7280",
        "dark-primary": "#F59E0B",
        "dark-secondary": "#FCD34D",
        "dark-accent": "#FDE68A",
        "dark-light": "#1F2937",
        "dark-dark": "#111827",
        "dark-text": "#F9FAFB",
        "dark-muted": "#9CA3AF",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
